version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Butterfly5?
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: library_redis
    ports:
      - "6380:6379"

  minio:
    image: minio/minio
    container_name: library_minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: library_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata:
